name: flutter_tests
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.0
  flutter_hooks: ^0.18.0
  hooks_riverpod: ^2.0.0-dev.0
  flutter_redux: ^0.8.2
  flutter_bloc: ^8.0.0
  get_it: ^7.2.0
  mobx: ^2.0.6+1
  flutter_mobx: ^2.0.3+2
  binder: ^0.4.0
  get: ^4.6.1
  flutter_command: ^2.0.1
  states_rebuilder: ^5.2.0
  flutter_triple: ^1.2.6
  get_it_mixin: ^3.1.3




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner: ^2.1.7
  mobx_codegen: ^2.0.5+2
flutter:
  uses-material-design: true